# fly.toml app configuration file generated for bluesky-link-archiver on 2024-12-10T12:00:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bluesky-link-archiver'
primary_region = 'iad'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
